name: OSV-Scanner with SBOM

on:
  schedule:
    - cron: "2 * * * *"
  push:
    branches: [master]

permissions:
  actions: read
  security-events: write
  contents: read

jobs:
  osv-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # Setup Go environment (required for osv-scanner installation)
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        
    # Install OSV-Scanner (correct method )
    - name: Install OSV-Scanner
      run: |
        go install github.com/google/osv-scanner/v2/cmd/osv-scanner@latest
        echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
        osv-scanner --version

    # Install build tools and Syft
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake
        curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Install Python environment 
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        
    - name: Install conan
      run: |
          pip install "conan>=2.0" --upgrade
          conan profile detect --force
                      
    - name: Linux build
      run: |
          mkdir -p build && cd build
          conan install .. --output-folder=. --build=missing    
          conan graph info . --format=json > conansbom.cdx.json
          echo "CONAN_SBOM file contents:"
          cat $GITHUB_WORKSPACE/conansbom.cdx.json
          cmake .. -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DBUILD_TESTING=TRUE -DBUILD_SHARED_LIBS=TRUE -DCMAKE_BUILD_TYPE=Release
          cmake --build .  --config Release --target install
          ls -la

    # Syft Generate SBOM
    - name: Generate SBOM
      run: |
        # Scan only the build directory where dependencies are installed
        syft scan dir:./build dir:~/.conan/data \
          --scope all-layers \
          --output cyclonedx-json=$GITHUB_WORKSPACE/sbom.cdx.json \
          --source-name "${{ github.repository }}" \
          --source-version "${{ github.sha }}"
        
        # Verify SBOM was created
        if [ ! -f "$GITHUB_WORKSPACE/sbom.cdx.json" ]; then
          echo "Error: SBOM file was not generated"
          exit 1
        fi

    - name: Debug - Show SBOM contents
      run: |
        echo "Current directory:"
        pwd
        echo "Going to dependency directory:"
        cd $GITHUB_WORKSPACE/build && ls -la && cd $GITHUB_WORKSPACE/ && ls -la
        echo "SBOM file contents:"
        cat $GITHUB_WORKSPACE/sbom.cdx.json
        # Check minimum requirements
        jq '.metadata.component.name' $GITHUB_WORKSPACE/sbom.cdx.json
        echo "Current directory:"
        pwd && ls -la

    #combine syft and conan sbom
    - name: Combine SBOMs
      run: |
        jq '.components = ($conan.components + $syft.components | unique)' \
          --slurpfile conan sbom_conan.cdx.json \
          --slurpfile syft sbom_syft.cdx.json \
          sbom_conan.cdx.json > sbom_final.cdx.json
            
    # Scan with explicit CycloneDX format
    - name: Run vulnerability scan
      run: |
           osv-scanner --licenses --format=json --output=$GITHUB_WORKSPACE/licenses.json --sbom=$GITHUB_WORKSPACE/sbom_final.cdx.json
           echo "License file contents:"
           cat $GITHUB_WORKSPACE/licenses.json
           osv-scanner --format=json --output=$GITHUB_WORKSPACE/results.json --sbom=$GITHUB_WORKSPACE/sbom_final.cdx.json
           # Check if results were generated
           if [ ! -f "$GITHUB_WORKSPACE/results.json" ]; then
             echo "Error: No scan results generated"
             exit 1
           else
             echo "Scan results:"
             cat $GITHUB_WORKSPACE/results.json
           fi
           
    # Upload results
    - name: Upload scan results
      uses: actions/upload-artifact@v4
      with:
        name: vulnerability-scan-results
        path: ${{ github.workspace }}/results.json
